#Import('bwt_env')

Import('aligners_env')

bwt_test_env = aligners_env.Clone()

#bwt_test_env['objects'] = []
		      
bwt_test_env['CFLAGS'] += ' -m64 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -O9 -fPIC -std=c99 -DFM_COMP_64' #-DCSALIB_SEARCH -msse4.2 -DVERBOSE_DBG
bwt_test_env['LINKFLAGS'] += ['-fopenmp']

bwt_test_env['objects'].insert(0, 'preprocess_dbwt.c')
preprocess_dbwt = bwt_test_env.Program('../bin/preprocess_dbwt', source = bwt_test_env['objects'])
bwt_test_env['objects'].pop(0)

bwt_test_env['objects'].insert(0, 'preprocess_dbwt_csalib.c')
preprocess_dbwt_csalib = bwt_test_env.Program('../bin/preprocess_dbwt_csalib',  source = bwt_test_env['objects']) 
bwt_test_env['objects'].pop(0)

bwt_test_env['objects'].insert(0, 'exact_search.c')
exact_search = bwt_test_env.Program('../bin/exact_search', source = bwt_test_env['objects'])
bwt_test_env['objects'].pop(0)

bwt_test_env['objects'].insert(0, 'inexact_search.c')
inexact_search = bwt_test_env.Program('../bin/inexact_search', source = bwt_test_env['objects'])
bwt_test_env['objects'].pop(0)

#print bwt_test_env['objects']
