import os

Import('aligners_env')

bwt_env = aligners_env.Clone()
bwt_env['objects'] = []

formats = ['csalib', 'dbwt', 'search', 'test']
for dir in formats:
    SConscript(os.path.join(dir, 'SConscript'), exports = ['aligners_env', 'bwt_env'])

bwt_env.Object(Split('bwt_commons.c genome.c bwt.c'))
#aligners_env['objects'] += aligners_env.Object(Split('bwt_commons.c'))
